name: Deploy Frontoffice to GitHub Pages

on:
  push:
    branches:
      - main   # muda aqui para a tua branch principal, se for outra

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy front/dist to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./front/dist
